### ISSUE TITLE
Do you work for the state of CA?

### ISSUE THREAD

**Issue by PySimpleGUI** [gbroiles/si100#2]
Wondering if you created this to help yourself or if it's for the state and/or other users.

**Comment by gbroiles** [comment]
No, I don't have any connection with CA, I just wanted to work on filling PDF forms and this seemed like a pretty simple one to start with. I'm on the board of a local nonprofit and we needed to fill this out, so it was on my mind. I thought it might be useful to others. 

By the way, thanks for your helpful package! It makes GUI development a lot easier than it used to be.
